apiVersion: v1
kind: Service
metadata:
  name: {{ include "mediawiki.fullname" . }}
  labels:
    {{- include "mediawiki.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mediawiki.service.type }}
  ports:
    - port: {{ .Values.mediawiki.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "mediawiki.selectorLabels" . | nindent 4 }}
