apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mariadb.name | quote }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "mariadb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.mariadb.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mariadb.labels" . | nindent 8 }}
        {{- with .Values.mariadb.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.mariadb.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.mariadb.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.mariadb.name }}
          securityContext:
            {{- toYaml .Values.mariadb.securityContext | nindent 12 }}
          image: "{{ .Values.mariadb.image.repository }}:{{ .Values.mariadb.image.tag  }}"
          imagePullPolicy: {{ .Values.mariadb.image.pullPolicy }}
          ports:
            - name: {{ .Values.mariadb.name }}
              containerPort: {{ .Values.mariadb.service.port }}
              protocol: TCP
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mariadb.name }}-secret
                  key: MARIADB_ROOT_PASSWORD
          resources:
            {{- toYaml .Values.mariadb.resources | nindent 12 }}
          volumeMounts:
          - name: mariadb-inituser
            mountPath: /docker-entrypoint-initdb.d
          {{- if .Values.mariadb.pvc.enabled }}
          - name: {{ .Values.mariadb.name }}-volume
            mountPath: /var/lib/mysql
          {{- end }}
      volumes:
      - name: mariadb-inituser
        secret:
          secretName: {{ .Values.mariadb.name }}-users
      {{- if .Values.mariadb.pvc.enabled }}
      - name: {{ .Values.mariadb.name }}-volume
        persistentVolumeClaim:
          claimName: {{ .Values.mariadb.name }}-pvc-claim
      {{- end }}
      {{- with .Values.mariadb.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mariadb.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mariadb.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
